### ISSUE TITLE
Function plotWeight

### ISSUE THREAD

**Issue by lara-sko** [BiostatOmics/MORE#1]
Is there an issue with the function ```plotWeight```, namely in the package it is called ```plotWeight``` but in vignette is written as ```plotweight```. Moreover,  in the example <https://github.com/BiostatOmics/MORE/blob/main/vignettes/UsersGuide.pdf> there is an argument ```targetF```, but the value and value type are not specified. Should string, list, vector or something else be used?

**Comment by maiderag** [comment]
Hi @lara-sko!
Thanks for using MORE and giving us feedback about the problems you are encountering. 
Some weeks ago, we did a massive push of MORE, in which we changed the majority of the names of the functions and the input variables MORE admits so that the package would be more intuitive for users. We changed the vignette according to those changes, but apparently, we failed to change it in the case of the function `plotWeight`. I have already changed the vignette to include the function with the correct spelling: `plotWeight`. 
According to the input, as I have included in the vignette now, targetF admits a string as input according to the target feature of which you want to create the plots. 
Thank you, and sorry for the bug; we are still polishing some functions.

**Comment by maiderag** [comment]
Hi @lara-sko!
Thanks for using MORE and giving us feedback about the problems you are encountering.
Some weeks ago, we did a massive push of MORE, in which we changed the majority of the names of the functions and the input variables MORE admits so that the package would be more intuitive for users. We changed the vignette according to those changes, but apparently, we failed to change it in the case of the function plotWeight. I have already changed the vignette to include the function with the correct spelling: plotWeight.
According to the input, as I have included in the vignette now, targetF admits a string as input according to the target feature of which you want to create the plots.
Thank you, and sorry for the bug; we are still polishing some functions.
